// Core Structured Schedule Data - Natively editable by the user without need for a backend.
const scheduleData = {
    "departments": [
        { "id": "IS", "name": "Information Systems (IS)" },
        { "id": "CS", "name": "Computer Science (CS)" }
    ],
    "studentGroups": {
        "2332002": "IS Group 1",
        "2432002": "IS Group 1",
        "2432003": "IS Group 1",
        "2432004": "IS Group 1",
        "2432005": "IS Group 1",
        "2432007": "IS Group 1",
        "2432008": "IS Group 1",
        "2432009": "IS Group 1",
        "2432010": "IS Group 1",
        "2432012": "IS Group 1",
        "2432013": "IS Group 1",
        "2432014": "IS Group 1",
        "2432015": "IS Group 1",
        "2432016": "IS Group 1",
        "2432017": "IS Group 1",
        "2432082": "IS Group 1",
        "2432018": "IS Group 1",
        "2432019": "IS Group 1",
        "2432026": "IS Group 1",
        "2432027": "IS Group 1",
        "2432028": "IS Group 1",
        "2432029": "IS Group 1",
        "2432030": "IS Group 1",
        "2432031": "IS Group 1",
        "2432033": "IS Group 1",
        "2432035": "IS Group 1",
        "2432036": "IS Group 1",
        "2432038": "IS Group 1",
        "2432040": "IS Group 1",
        "2432041": "IS Group 1",
        "2432042": "IS Group 1",
        "2432044": "IS Group 1",
        "2432045": "IS Group 2",
        "2432047": "IS Group 2",
        "2432049": "IS Group 2",
        "2432050": "IS Group 2",
        "2432051": "IS Group 2",
        "2432053": "IS Group 2",
        "2432054": "IS Group 2",
        "2432055": "IS Group 2",
        "2432056": "IS Group 2",
        "2432058": "IS Group 2",
        "2432059": "IS Group 2",
        "2432060": "IS Group 2",
        "2432064": "IS Group 2",
        "2432066": "IS Group 2",
        "2432068": "IS Group 2",
        "2432070": "IS Group 2",
        "2432072": "IS Group 2",
        "2432073": "IS Group 2",
        "2432074": "IS Group 2",
        "2432075": "IS Group 2",
        "2432076": "IS Group 2",
        "2432077": "IS Group 2",
        "2432078": "IS Group 2",
        "2432080": "IS Group 2",
        "2432083": "IS Group 2",
        "2432101": "IS Group 2",
        "2432104": "IS Group 2",
        "2432109": "IS Group 2",
        "2432111": "IS Group 2",
        "2432189": "IS Group 2",
        "2425028": "IS Group 2",
        "2431001": "CS Group 1",
        "2431002": "CS Group 1",
        "2431003": "CS Group 1",
        "2431004": "CS Group 1",
        "2431005": "CS Group 1",
        "2431006": "CS Group 1",
        "2431007": "CS Group 1",
        "2431008": "CS Group 1",
        "2431009": "CS Group 1",
        "2431010": "CS Group 1",
        "2431011": "CS Group 1",
        "2431012": "CS Group 1",
        "2431013": "CS Group 1",
        "2431014": "CS Group 1",
        "2431015": "CS Group 1",
        "2431016": "CS Group 1",
        "2431017": "CS Group 1",
        "2431018": "CS Group 1",
        "2431019": "CS Group 1",
        "2431020": "CS Group 1",
        "2431021": "CS Group 1",
        "2431022": "CS Group 1",
        "2431023": "CS Group 1",
        "2431024": "CS Group 1",
        "2431025": "CS Group 1",
        "2431026": "CS Group 1",
        "2431027": "CS Group 1",
        "2431028": "CS Group 1",
        "2431029": "CS Group 1",
        "2431030": "CS Group 1",
        "2431031": "CS Group 1",
        "2431032": "CS Group 1",
        "2431033": "CS Group 1",
        "2431034": "CS Group 1",
        "2431035": "CS Group 1",
        "2431036": "CS Group 1",
        "2431037": "CS Group 1",
        "2431038": "CS Group 1",
        "2431039": "CS Group 1",
        "2431040": "CS Group 1",
        "2431041": "CS Group 1",
        "2431042": "CS Group 1",
        "2431043": "CS Group 1",
        "2431044": "CS Group 1",
        "2431045": "CS Group 1",
        "2431046": "CS Group 1",
        "2431047": "CS Group 1",
        "2431048": "CS Group 1",
        "2431049": "CS Group 1",
        "2431050": "CS Group 1",
        "2431051": "CS Group 1",
        "2431052": "CS Group 1",
        "2431053": "CS Group 1",
        "2431054": "CS Group 1",
        "2431055": "CS Group 1",
        "2431056": "CS Group 1",
        "2431057": "CS Group 1",
        "2431058": "CS Group 1",
        "2431063": "CS Group 2",
        "2431064": "CS Group 2",
        "2431065": "CS Group 2",
        "2431066": "CS Group 2",
        "2431067": "CS Group 2",
        "2431068": "CS Group 2",
        "2431069": "CS Group 2",
        "2431070": "CS Group 2",
        "2431071": "CS Group 2",
        "2431072": "CS Group 2",
        "2431073": "CS Group 2",
        "2431074": "CS Group 2",
        "2431075": "CS Group 2",
        "2431076": "CS Group 2",
        "2431077": "CS Group 2",
        "2431078": "CS Group 2",
        "2431079": "CS Group 2",
        "2431080": "CS Group 2",
        "2431081": "CS Group 2",
        "2431082": "CS Group 2",
        "2431083": "CS Group 2",
        "2431084": "CS Group 2",
        "2431085": "CS Group 2",
        "2431086": "CS Group 2",
        "2431087": "CS Group 2",
        "2431088": "CS Group 2",
        "2431089": "CS Group 2",
        "2431090": "CS Group 2",
        "2431091": "CS Group 2",
        "2431092": "CS Group 2",
        "2431093": "CS Group 2",
        "2431094": "CS Group 2",
        "2431095": "CS Group 2",
        "2431096": "CS Group 2",
        "2431097": "CS Group 2",
        "2431098": "CS Group 2",
        "2431099": "CS Group 2",
        "2431100": "CS Group 2",
        "2431101": "CS Group 2",
        "2431102": "CS Group 2",
        "2431103": "CS Group 2",
        "2431104": "CS Group 2",
        "2431105": "CS Group 2",
        "2431106": "CS Group 2",
        "2431107": "CS Group 2",
        "2431108": "CS Group 2",
        "2431109": "CS Group 2",
        "2431110": "CS Group 2",
        "2431111": "CS Group 2",
        "2431112": "CS Group 2",
        "2431113": "CS Group 2"
    },
    "groups": {
        "IS": [
            {
                "name": "IS Group 1",
                "sessions": [
                    // { "courseId": "CS206", "courseName": "Computer Programming-2 (OOP)",                            "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS203", "courseName": "Computer Programming-2 (OOP)",                            "type": "Section", "day": "Thursday" , "start": "09:30", "end": "10:30", "location": "قاعة (1)"       , "groups": ["IS Group 1"]                                            , "instructor": "م/ عبدالله حلمي"     , "notes": "" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Lecture", "day": "Saturday" , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ احمد جمال"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Section", "day": "Monday"   , "start": "10:00", "end": "11:00", "location": "البلازا الخارجية", "groups": ["IS Group 1"]                                            , "instructor": "م/ مريم فياض"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Lecture", "day": "Tuesday"  , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ طارق مصطفي"     , "notes": "" },
                    // { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Section", "day": "Wednesday", "start": "10:00", "end": "11:00", "location": "البلازا الخارجية", "groups": ["IS Group 1"]                                            , "instructor": "م.م/ هبه فتحي"       , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Section", "day": "Monday"   , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["IS Group 1"]                                            , "instructor": "م.م/ هبه فتحي"       , "notes": "الميعاد والمحاضر غير مؤكدان" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Section", "day": "Tuesday"  , "start": "10:00", "end": "11:00", "location": "القاعة الجديدة" , "groups": ["IS Group 1"]                                            , "instructor": "م/ ديفيد كمال"       , "notes": "" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Lecture", "day": "Tuesday"  , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ ابراهيم سليم"   , "notes": "" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Lecture", "day": "Saturday" , "start": "12:15", "end": "13:15", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ كرم السيد"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Section", "day": "Wednesday", "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["IS Group 1"]                                            , "instructor": "م/ ابتهال يسري"      , "notes": "" }
                ]
            },
            {
                "name": "IS Group 2",
                "sessions": [
                    // { "courseId": "CS206", "courseName": "Computer Programming-2 (OOP)",                            "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS203", "courseName": "Computer Programming-2 (OOP)",                            "type": "Section", "day": "Tuesday"  , "start": "10:00", "end": "11:00", "location": "البلازا الخارجية",  "groups": ["IS Group 2"]                                             , "instructor": "م/ نادر جمال"        , "notes": "OS ومرة Programming احتمال مرة" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Lecture", "day": "Saturday" , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ احمد جمال"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Section", "day": "Wednesday", "start": "12:00", "end": "13:00", "location": "السيمينار"      , "groups": ["IS Group 2"]                                            , "instructor": "م/ نانسي عبدالحليم"  , "notes": "" },
                    { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Lecture", "day": "Tuesday"  , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ طارق مصطفي"     , "notes": "" },
                    // { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Section", "day": "Wednesday", "start": "10:00", "end": "11:00", "location": "القاعة الجديدة" , "groups": ["IS Group 2"]                                            , "instructor": "م/ ابراهيم عبدالله"  , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Section", "day": "Wednesday", "start": "10:30", "end": "11:30", "location": "البلازا الخارجية", "groups": ["IS Group 2"]                                            , "instructor": "م/ عبدالله حلمي"   , "notes": "" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Section", "day": "Tuesday"  , "start": "10:00", "end": "11:00", "location": "البلازا الخارجية", "groups": ["IS Group 2"]                                            , "instructor": "م/ نادر جمال"        , "notes": "OS ومرة Programming احتمال مرة" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Lecture", "day": "Tuesday"  , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ ابراهيم سليم"   , "notes": "" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Lecture", "day": "Saturday" , "start": "12:15", "end": "13:15", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ كرم السيد"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Section", "day": "Wednesday", "start": "12:00", "end": "13:00", "location": "البلازا الخارجية", "groups": ["IS Group 2"]                                            , "instructor": "م/ ابتهال يسري"      , "notes": "" }
                ]
            }
        ],
        "CS": [
            {
                "name": "CS Group 1",
                "sessions": [
                    // { "courseId": "CS206", "courseName": "Computer Programming-2 (OOP)",                            "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS203", "courseName": "Computer Programming-2 (OOP)",                            "type": "Section", "day": "Wednesday", "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2"]                              , "instructor": "م/ اسراء ماجد"       , "notes": "" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Lecture", "day": "Saturday" , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ احمد جمال"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Section", "day": "Monday"   , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1"]                                            , "instructor": "م/ مريم فياض"        , "notes": "احتمال الميعاد يتغير" },
                    // { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Section", "day": "Monday"   , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["CS Group 1"]                                            , "instructor": "م/ ابراهيم عبدالله"  , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Lecture", "day": "Tuesday"  , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ طارق مصطفي"     , "notes": "" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Section", "day": "Monday"   , "start": "12:00", "end": "13:00", "location": "البلازا الخارجية", "groups": ["CS Group 1"]                                            , "instructor": "م/ عبدالله حلمي"   , "notes": "" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Lecture", "day": "Tuesday"  , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ ابراهيم سليم"   , "notes": "" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Section", "day": "Tuesday"  , "start": "10:00", "end": "11:00", "location": "القاعة الجديدة" , "groups": ["CS Group 1"]                                            , "instructor": "م/ ديفيد كمال"       , "notes": "" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Lecture", "day": "Saturday" , "start": "12:15", "end": "13:15", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ كرم السيد"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Section", "day": "Wednesday", "start": "12:30", "end": "13:30", "location": "القاعة الجديدة" , "groups": ["CS Group 1", "CS Group 2"]                              , "instructor": "م/ اسراء ماجد"       , "notes": "" }
                ]
            },
            {
                "name": "CS Group 2",
                "sessions": [
                    // { "courseId": "CS206", "courseName": "Computer Programming-2 (OOP)",                            "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS203", "courseName": "Computer Programming-2 (OOP)",                            "type": "Section", "day": "Wednesday", "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2"]                              , "instructor": "م/ اسراء ماجد"       , "notes": "" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Lecture", "day": "Saturday" , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ احمد جمال"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS201", "courseName": "Multimedia",                                              "type": "Section", "day": "Wednesday", "start": "11:00", "end": "12:00", "location": "السيمينار"      , "groups": ["CS Group 2"]                                            , "instructor": "م/ نانسي عبدالحليم"  , "notes": "" },
                    // { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Section", "day": "Monday"   , "start": "09:00", "end": "10:00", "location": "القاعة الجديدة" , "groups": ["CS Group 2"]                                            , "instructor": "م.م/ هبه فتحي", "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "CS204", "courseName": "Data Structure",                                          "type": "Lecture", "day": "Tuesday"  , "start": "09:00", "end": "10:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ طارق مصطفي"     , "notes": "" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Lecture", "day": "Thursday" , "start": "11:30", "end": "12:30", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.م.د/ سارة شهاب"    , "notes": "Programming واسبوع Web اسبوع" },
                    { "courseId": "CS206", "courseName": "Web Design and Development",                              "type": "Section", "day": "Wednesday", "start": "09:00", "end": "10:00", "location": "البلازا الداخلية", "groups": ["CS Group 2"]                                            , "instructor": "م.م/ هبه فتحي"       , "notes": "الميعاد والمحاضر غير مؤكدان" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Lecture", "day": "Tuesday"  , "start": "11:00", "end": "12:00", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "ا.د/ ابراهيم سليم"   , "notes": "" },
                    { "courseId": "CS205", "courseName": "Operating Systems-1",                                     "type": "Section", "day": "Wednesday", "start": "غير محدد", "end": "غير محدد", "location": "ONLINE" , "groups": ["CS Group 2"]                                            , "instructor": "م.م/ سلمى رأفت"      , "notes": "احتمال المحاضر يتغير \\ الميعاد غير مؤكد" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Lecture", "day": "Saturday" , "start": "12:15", "end": "13:15", "location": "البلازا الخارجية", "groups": ["CS Group 1", "CS Group 2", "IS Group 1", "IS Group 2"]  , "instructor": "د/ كرم السيد"        , "notes": "احتمال الميعاد يتغير" },
                    { "courseId": "IS205", "courseName": "Introduction to Operation Research & Decision Support",   "type": "Section", "day": "Wednesday", "start": "12:30", "end": "13:30", "location": "القاعة الجديدة" , "groups": ["CS Group 1", "CS Group 2"]                              , "instructor": "م/ اسراء ماجد"       , "notes": "" }
                ]
            }
        ]
    }
};
